### ISSUE TITLE
Please mandate hahsing.enabled = true when matrix.v2 = true

### ISSUE THREAD

**Issue by rda0** [ma1uta/ma1sd#26]
This relates to https://github.com/vector-im/riot-web/issues/12235

> As as you type something that looks like an email address (xxx@yyy.zz) with a domain.tld part, a match is found and shown, but after a few milliseconds it shows: Something went wrong!. The dev-tools console shows: Error: "Unsupported identity server: bad response". The ma1sd log and the tcpdump both look good.
I noticed this on ma1sd 2.2.0 and 2.3.0 with synapse 1.6.1 and 1.9.1. The problem occurs when using Riot web/desktop on Linux and Windows

The error described above occurs when the v2 API is enabled but hashing left disabled (default):

```yaml
matrix:
  v2: true

hashing:
  enabled: false
```

When the browser requests `/_matrix/identity/v2/hash_details` it gets the following response:

```json
{
  "algorithms": []
}
```

Riot then throws `Unsupported identity server: bad response`

I am not sure if the response should at least look look like this:

```json
{
  "lookup_pepper": "x",
  "algorithms": []
}
```

According to [MSC2134](https://github.com/matrix-org/matrix-doc/blob/hs/hash-identity/proposals/2134-identity-hash-lookup.md), a valid pepper value of at least length 1 is required:

> The name lookup_pepper was chosen in order to account for pepper values being returned for other endpoints in the future. The contents of lookup_pepper MUST match the regular expression [a-zA-Z0-9]+, whether hashing is being performed or not. When no hashing is occuring, a valid pepper value of at least length 1 is still required.

When hashing is enabled, the error does not occur:

```yaml
hashing:
  enabled: true
  pepperLength: 20
  rotationPolicy: per_requests
  hashStorageType: sql
  algorithms:
    - sha256
  delay: 2m
  requests: 10
```

If enabling hashing is a requirement for enabling v2 API, it should be documented.
