### ISSUE TITLE
Unshared emails are treated as shared

### ISSUE THREAD

**Issue by mrjohnson22** [ma1uta/ma1sd#27]
Emails bound to a mxid are returned by `/_matrix/identity/v2/lookup` even though they were never validated for sharing through ma1sd, and despite the fact that `session_3pid` table of ma1sd's backend storage is blank.

This happens to me when using the synapseSql identity store, the postgresql backend, and the v2 API with hashing. I haven't tried other identity stores, and I am restricted to using the postgresql backend.

My config:

```
matrix:
  domain: 'domain'
  v1: true
  v2: true
  ## Remove default matrix-org server
  identity:
    servers:
      myOtherServers: []

server:
  name: 'identity.domain'

key:
  path: '/var/lib/ma1sd/keys'

storage:
  backend: postgresql
  provider:
    postgresql:
      database: '//localhost/ma1sd'
      username: 'user'
      password: 'pass'

threepid:
  medium:
    email:
      identity:
        from: "noreply-id@domain"
        name: "Name"
      connectors:
        smtp:
          host: "localhost"
          tls: 0
          port: 25

hashing:
  enabled: true
  pepperLength: 20
  rotationPolicy: per_requests
  hashStorageType: in_memory
  algorithms:
    - sha256

synapseSql:
  enabled: true
  type: 'postgresql'
  connection: '//localhost/synapse?user=synapse_user&password=pass'
  lookup:
    query: 'select user_id as mxid, medium, address from user_threepids'
  legacyRoomNames: false

logging:
  root: debug
  app: debug
```
