### ISSUE TITLE
Multi-Tenant LDAP

### ISSUE THREAD

**Issue by rbicelli** [ma1uta/ma1sd#46]
Hello! I was testing Matrix-Synapse with mxisd but I stopped tests because my requirements are tied tied multiple LDAP Servers (Different Active Directory Domains with trust relationships)
Is ma1sd capable to authenticate across different ldap servers?  
Thanks

**Comment by piezza** [comment]
Yes, that works really nice. You need to have global catalog enabled on your DC (listens usually on port 3268, only in GC you will see the whole forrest). Then you can add multiple baseDn:
```
ldap:
  enabled: true
  connection:
    host: 'dc.local'
    port: 3268
    baseDNs:
      - 'OU=intern,DC=company1,DC=loc'
      - 'OU=intern,DC=company2,DC=loc'
 attribute:
      uid:
        type: 'uid'
        value: 'sAMAccountName'
      name: 'cn'
```
On our setup the sAMAccountName are unique over all Domains. If this isn't the case at your setup maybe you need to setup some rules to rewrite the uid in ma1sd.

**Comment by rbicelli** [comment]
My setup is trusted domain with multiple forests, so I have independent LDAP Servers.

**Comment by piezza** [comment]
I really wonder how you handle other applications which need cross domain user authentication over LDAP. In general you install a global catalog and do all binds and searches over this service then. Global catalog should mirror all objects in your AD Forrests trust if configured properly.

**Comment by rbicelli** [comment]
In applications we use (dovecot, sogo, nextcloud) is possible to add multiple authentications sources, one per domain. Will try the global catalog way and report here if it works for my particular setup.
Thanks!

**Comment by rbicelli** [comment]
I adjusted the trust relationships by making them bidirectional. No matter what I do I cannot login.
My settings:
```
ldap:
  enabled: true
  lookup: true
  connection:
    host: 'dc.domain0.ad'
    port: 3268
    bindDn: '...bind DN'
    bindPassword: '.. bind pw'
    baseDNs:
      - 'DC=domain0,DC=ad'
      - 'DC=ddomain1,DC=ad'
      - 'DC=domain2,DC=ad'
    attribute:
      uid:
        type: 'uid'
        value: 'sAMAccountName'
      name: 'displayName'
      threepid:
        email:
          - 'mail'
        msisdn:
          - 'phone'
          - 'mobile'
```
When tracing LDAP packets I see query performed on both three domains but lookup returns 0 results, even if entry exists. Search is performed with filter (sAMAccountName=username).

In logs I see
`Jul 20 14:57:22 riotim ma1sd[84537]: [XNIO-1 task-1] INFO io.kamax.mxisd.http.undertow.handler.auth.RestAuthHandler - Requested to check credentials for @username:mtx.mydomain`
and
`Jul 20 14:57:23 riotim ma1sd[84537]: [XNIO-1 task-1] INFO io.kamax.mxisd.backend.ldap.LdapAuthProvider - No match were found for @username:mtx.mydomain`
