### ISSUE TITLE
Missing 3PIDs in riot-web

### ISSUE THREAD

**Issue by rootuser** [ma1uta/ma1sd#48]
I would like to point out a problem that may be due to a bug in ma1sd.

The original issue was first reported in the riot-web bug list, see here: [https://github.com/vector-im/riot-web/issues/13033#](url)

In short, the problem is that no 3PIDs are shown in the settings page of riot-web, as well as in riotX Android app. In the old riot Android app, 3PIDs are shown though.

When I noticed the followin error in the browsers javascript console:
> Access to XMLHttpRequest at 'https://matrix.mydomain.de/_matrix/identity/v2/account/register' from origin 'https://riot.mydomain.de' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

it seemed to me the problem might be caused by a wrongly configured reverse proxy.

I contacted the developer of matrix-docker-ansible-deploy, as my installation is done via his script. You can find my report in his issue list at [https://github.com/spantaleev/matrix-docker-ansible-deploy/issues/505](url)

It turned out that when riot-web accessed the identity server, an Access-Control-Allow-Origin header was missing, which denied access.
This problem was finally fixed, see [https://github.com/spantaleev/matrix-docker-ansible-deploy/pull/511](url)

The reason why I am addressing you is that the absence of the old bug now reveals a new one: in the current version I get the message:
Unable to reach identity server at https://matrix.mydomain.de to check for 3PIDs bindings in Settings
Error: Unsupported identity server: bad response

Since I use ma1sd as identity server and since e.g. the login works without problems I wonder if the described behaviour might be a bug in ma1sd.

It would be great if you could comment on this.

Best, Tom

**Comment by ma1uta** [comment]
Hello. Sorry for the late answer.

I double checked the code and ma1sd always return CORS headers.

I think this issue occurs because V2 API was disabled in the previous version. In the next release V2 will be enabled by default. Lets check again after the release.

**Comment by jmastr** [comment]
@ma1uta I am using ma1sd v2.4.0 with V2 enabled, but the problem still persists. Any ideas how I could debug it?

**Comment by jmastr** [comment]
I needed to add:
```
hashing:
  enabled: true # enable or disable the hash lookup MSC2140 (default is false)
  pepperLength: 20 # length of the pepper value (default is 20)
  rotationPolicy: per_requests # or `per_seconds` how often the hashes will be updating
  hashStorageType: sql # or `in_memory` where the hashes will be stored
  algorithms:
    - none   # the same as v1 bulk lookup
    - sha256 # hash the 3PID and pepper.
  delay: 2m # how often hashes will be updated if rotation policy = per_seconds (default is 10s)
  requests: 10 # how many lookup requests will be performed before updating hashes if rotation policy = per_requests (default is 10)
```
https://github.com/ma1uta/ma1sd/blob/master/docs/MSC2140_MSC2134.md#hash-lookup

to my config. After that, the error disappeared.
