### ISSUE TITLE
M_UNAUTHORIZED: Supplied credentials are invalid

### ISSUE THREAD

**Issue by T3chTobi** [ma1uta/ma1sd#73]
Hello! I want to use ma1sd as an identity server with registering and inviting users enabled. This is the configuration I'm using:
```
dns:
    overwrite:
        homeserver:
            client:
            -   name: matrix.domain.com
                value: http://matrix-corporal:41080
hashing:
    algorithms:
    - none
    - sha256
    delay: 2m
    enabled: true
    hashStorageType: sql
    pepperLength: 20
    requests: 10
    rotationPolicy: per_requests
key:
    path: /var/ma1sd/sign.key
matrix:
    domain: domain.com
    v1: true
    v2: true
server:
    name: matrix.domain.com
storage:
    provider:
        sqlite:
            database: /var/ma1sd/ma1sd.db
synapseSql:
    connection: //matrix-postgres/homeserver?user=my-user&password=top-secret-123
    enabled: true
    type: postgresql
threepid:
    medium:
        email:
            connectors:
                smtp:
                    host: matrix-mailer
                    login: null
                    password: null
                    port: 8025
                    tls: 0
            identity:
                from: info@domain.com
```

I can register a new user. But when I want to invite a user to a room or when I want to add an email to the user in the settings, I'm getting this error:
```
POST https://matrix.domain.com/_matrix/identity/v2/account/register 401
M_UNAUTHORIZED: Supplied credentials are invalid
```

What can I do? Can someone send my a full configuration that I can use?
