### ISSUE TITLE
Invitation 3pid not working correctly

### ISSUE THREAD

**Issue by T3chTobi** [ma1uta/ma1sd#82]
This is the problem:

1. I invite a new user by email to a room
2. New user creates a new account with the email he was invited
3. nothing (user should be invited into the invited room)

This is my `ma1sd.yaml`:
```
dns:
    overwrite:
        homeserver:
            client:
            -   name: matrix.domain.com
                value: http://matrix-corporal:41080
hashing:
    algorithms:
    - none
    - sha256
    delay: 2m
    enabled: true
    hashStorageType: sql
    pepperLength: 20
    requests: 10
    rotationPolicy: per_requests
key:
    path: /var/ma1sd/sign.key
logging:
    app: info
    requests: false
    root: error
matrix:
    domain: domain.com
    v1: true
    v2: true
policy:
    policies:
        privacy_policy:
            terms:
                de:
                    name: Datenschutzerklärung
                    url: https://www.domain.com/datenschutz
                en:
                    name: privacy policy
                    url: https://www.domain.com/datenschutz
            version: 1.0
        terms_of_service:
            terms:
                de:
                    name: AGB
                    url: https://www.domain.com/agb
                en:
                    name: terms of service
                    url: https://www.domain.com/agb
            version: 1.0
register:
    allowed: false
    invite: true
    policy:
        allowed: true
        threepid:
            email:
                domain:
                    blacklist: null
                    whitelist: null
server:
    name: matrix.domain.com
storage:
    backend: postgresql
    provider:
        postgresql:
            database: //matrix-postgres:5432/matrix_ma1sd
            password: secret-password
            username: matrix_ma1sd
synapseSql:
    connection: //matrix-postgres/homeserver?user=synapse-postgres&password=secret-password
    enabled: true
    identity:
        enabled: true
        query: select user_id as uid, medium, address from user_threepids where medium = ? and address = ?
    lookup:
        query: select user_id as mxid, medium, address from user_threepids
    type: postgresql
threepid:
    medium:
        email:
            connectors:
                smtp:
                    host: matrix-mailer
                    login: null
                    password: null
                    port: 8025
                    tls: 0
            generators:
                template:
                    generic:
                        matrixId: /etc/ma1sd/mxid-template.eml
                    invite: /etc/ma1sd/invite-template.eml
                    session:
                        unbind:
                            notification: /etc/ma1sd/unbind-notification.eml
                        validation: /etc/ma1sd/validate-template.eml
            identity:
                from: info@domain.com
view:
    session:
        onTokenSubmit:
            failure: /etc/ma1sd/tokenSubmitFailure.html
            success: /etc/ma1sd/tokenSubmitSuccess.html
```
