### ISSUE TITLE
UI of Terms not working

### ISSUE THREAD

**Issue by T3chTobi** [ma1uta/ma1sd#83]
I'm using the terms feature of `ma1sd`: https://github.com/ma1uta/ma1sd/blob/master/docs/MSC2140_MSC2134.md#terms
But it is not working with this code:
```
policy:
    policies:
      terms_of_service:
        version: 1.0
        terms:
          de:
            name: AGB
            url: https://www.domain.de/agb
          en:
            name: terms of service
            url: https://www.domain.de/agb
        #regexp:
        #  - '/_matrix/identity/v2/account.*'
        #  - '/_matrix/identity/v2/hash_details'
        #  - '/_matrix/identity/v2/lookup'
```

I'm not using a `.html` file for the url, but a `.php` script without the extension.

`element-web` is calling the `/terms` endpoint and the correct JSON is in the response, but the UI of `element-web` does not pop up to ask if the user accepts the terms.

<img width="745" alt="Bildschirmfoto 2021-01-03 um 16 39 58" src="https://user-images.githubusercontent.com/7794412/103490493-77269480-4e1c-11eb-9fcb-b79d28ff25bc.png">

These are the called endpoints and here is an article from `matrix-org` describing the process: https://github.com/matrix-org/matrix-doc/blob/master/proposals/2140-terms-of-service-2.md
